name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Make env.sh executable and create .env
      - name: Set up environment variables
        run: |
          chmod +x ./deployment/production/env.sh
          ./deployment/production/env.sh

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/speed-engine:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/speed-engine:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure GCP project
      - name: Configure GCP project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Connect to existing GCP instance and deploy container
      - name: Deploy Docker container to existing instance
        run: |
          gcloud compute ssh instance-20241028-104014 --zone us-central1-c --command "
            sudo apt update &&
            sudo apt install -y docker.io &&
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin &&
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/speed-engine:latest &&
            sudo docker stop speed-engine-container || true &&
            sudo docker rm speed-engine-container || true &&
            sudo docker run -d --restart always --name speed-engine-container -p 3021:3021 ${{ secrets.DOCKER_USERNAME }}/speed-engine:latest
          "
