name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Configure GCP project
      - name: Configure GCP project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      # Authenticate Docker with GCP
      - name: Authenticate Docker with GCP
        run: |
          gcloud auth configure-docker gcr.io

      # Pull Docker image from Docker Hub
      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Deploy Docker image on GCP
      - name: Deploy Docker container
        run: |
          gcloud compute instances update-container instance-20241028-104014 --zone us-central1-c --container-image ${{ secrets.DOCKER_USERNAME }}/my-app:latest --tags=http-server,https-server --container-restart-policy always
