prod-build:
    stage: build
    image: docker:stable
    services:
        - docker:dind
    before_script:
        - chmod +x ./deployment/production/env.sh
        - ./deployment/production/env.sh
        - docker info
        - docker login ghcr.io -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
    script:
        - docker build --pull -t "$CI_REGISTRY_IMAGE" .
        - docker push "$CI_REGISTRY_IMAGE"
        - echo "Build successfully!"
    after_script:
        - docker logout ${CI_REGISTRY}
    only:
        - main

prod-deploy:
    stage: deploy
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan $VM_PROD >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
    script:
        - ssh $USER_PROD@$VM_PROD "docker pull ghcr.io/danielpnjt/speed-engine:latest"
        - ssh $USER_PROD@$VM_PROD "docker stop speed-engine || true && docker rm speed-engine || true"
        - ssh $USER_PROD@$VM_PROD "docker run -p 5000:5000 -d --name speed-engine ghcr.io/danielpnjt/speed-engine:latest"
    only:
        - tags
        - main
    when: manual